// HTTP 状态码
const HTTP_STATUS = {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500,
};

// Operation 常量
const OPERATIONS = {
    // 成功操作
    SUCCESS: "SUCCESS", // 200
    CREATED: "CREATED", // 201

    // 客户端错误
    BAD_REQUEST: "BAD_REQUEST", // 400
    UNAUTHORIZED: "UNAUTHORIZED", // 401
    FORBIDDEN: "FORBIDDEN", // 403
    NOT_FOUND: "NOT_FOUND", // 404
    VALIDATION_ERROR: "VALIDATION_ERROR", // 400

    // 服务器错误
    ERROR_HANDLER: "ERROR_HANDLER", // 500
    DATABASE_ERROR: "DATABASE_ERROR", // 500
    NETWORK_ERROR: "NETWORK_ERROR", // 500
    UNKNOWN_ERROR: "UNKNOWN_ERROR", // 500
};

// 资源类型
const RESOURCE_TYPES = {
    SERVER: "Server",
    DATABASE: "Database",
    NETWORK: "Network",
    CLIENT: "Client",
    CLIENT_ERROR: "ClientError",
    SERVER_ERROR: "ServerError",
    UNKNOWN: "Unknown",
};

// HTTP状态码与Operation的映射关系
const STATUS_TO_OPERATION = {
    [HTTP_STATUS.OK]: OPERATIONS.SUCCESS,
    [HTTP_STATUS.CREATED]: OPERATIONS.CREATED,
    [HTTP_STATUS.BAD_REQUEST]: OPERATIONS.BAD_REQUEST,
    [HTTP_STATUS.UNAUTHORIZED]: OPERATIONS.UNAUTHORIZED,
    [HTTP_STATUS.FORBIDDEN]: OPERATIONS.FORBIDDEN,
    [HTTP_STATUS.NOT_FOUND]: OPERATIONS.NOT_FOUND,
    [HTTP_STATUS.INTERNAL_SERVER_ERROR]: OPERATIONS.ERROR_HANDLER,
};

module.exports = {
    HTTP_STATUS,
    OPERATIONS,
    STATUS_TO_OPERATION,
    RESOURCE_TYPES,
};
